# Key components of supervised learning

- data to learn from 
- model of how to transform the data
- objective function to qualify how well the model is doing
- an algorithm to adjust the model's params to optimize objective function

Loss function for numerical values : squared error
Loss function for Classification : minimize error rate, cross entroy




In [1]:
import torch


In [3]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [4]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [5]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [6]:
x.grad

In [7]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [8]:
y.backward()

In [9]:
x.grad

tensor([ 0.,  4.,  8., 12.])